-- GERANDO OS CANDIDATOS INSCRITOS ACUMULADOS

-- GERA LOG


INSERT INTO IE_CANDIDATO_INSCRITO_ACUMULADO_V3_LOG
SELECT	*, getdate()DT_LOG 
FROM	IE_CANDIDATO_INSCRITO_ACUMULADO_V3
Where	ANO	IN (
				SELECT	DISTINCT ANO
				FROM	[POLARIS02\BDIESBPROD].LYCEUM.DBO.IE_LY_OPCOES_APP
				WHERE	APLICACAO in ( 'VESTIBULAR','VESTIBULAR_EAD_TRIMESTRAL')
				)

-- LIMPA A TB
delete IE_CANDIDATO_INSCRITO_ACUMULADO_V3 where ano IN (
														SELECT	DISTINCT ANO
														FROM	[POLARIS02\BDIESBPROD].LYCEUM.DBO.IE_LY_OPCOES_APP
														WHERE	APLICACAO in ( 'VESTIBULAR','VESTIBULAR_EAD_TRIMESTRAL')
														)


-- GERA OS DADOS
DECLARE  @DATA DATETIME
		

	DECLARE cursor_gera_financeiro CURSOR FOR 

		select	convert(varchar, DATA, 102) as data
		from	[POLARIS02\BDIESBPROD].LYCEUM.DBO.IE_date
		where	data >='2017-10-24 09:17:18.783' AND data <= getdate()+1
		ORDER BY DATA

	OPEN cursor_gera_financeiro 
	FETCH NEXT FROM cursor_gera_financeiro INTO @DATA
      
	WHILE @@FETCH_STATUS = 0 
	BEGIN 



			INSERT INTO IE_CANDIDATO_INSCRITO_ACUMULADO_V3
			SELECT	A.CANDIDATO
					,A.CONCURSO
					,B.ANO
					,B.SEMESTRE
					, CV.CURSO
					/*, CASE	WHEN GRUPO_CURSO IS NULL 
							THEN CU.FACULDADE 
							ELSE GRUPO_CURSO 
							END	 CAMPUS*/
					,COALESCE(GRUPO_CURSO, COALESCE(B.FACULDADE, CU.FACULDADE)) CAMPUS
					,CASE	WHEN COALESCE(INEP_PRESENCIAL, 'P') = 'P' THEN 'Presencial' 
							WHEN COALESCE(INEP_PRESENCIAL, 'P') = 'D' THEN 'Ead' 
							WHEN COALESCE(INEP_PRESENCIAL, 'P') = 'S' THEN 'Semi-Presencial' 
							ELSE 'Presencial'
							END MODALIDADE
					,CASE	WHEN b.CONCURSO LIKE 'IPS%ESPECIAL%'  or b.TIPO_CONCURSO ='Especial' THEN 'CONCURSO ESPECIAL'
															WHEN b.TIPO_CONCURSO  = 'Tradic'  THEN 'VESTIBULAR TRADICIONAL'                        
															WHEN b.TIPO_CONCURSO = 'VestAgend'  THEN 'VESTIBULAR AGENDADO'                        
															WHEN b.TIPO_CONCURSO = 'DCS'   THEN 'DCS'                        
															WHEN b.TIPO_CONCURSO = 'Transf'  THEN 'TRANSFERENCIA'                        
															WHEN b.TIPO_CONCURSO = 'MudancaCurso' THEN 'MUDANCA DE CURSO'                      
															WHEN b.TIPO_CONCURSO = 'Prouni'  THEN 'PROUNI'                        
															WHEN (b.CONCURSO LIKE  '%GDF%' or b.Tipo_concurso like '%GDF%')THEN 'GDF'
															WHEN b.CONCURSO LIKE  'IPS%ENEM%' or b.TIPO_CONCURSO ='ENEM' THEN 'ENEM'                        
															when b.CONCURSO LIKE  'IPSEAD%'  or b.TIPO_CONCURSO ='EADGraduacao' THEN 'EAD'  
															WHEN b.TIPO_CONCURSO='INTERESSE'   THEN 'INTERESSE'  
															Else 'Concurso não informado'
															END TIPO_CONCURSO
					,DT_INSCRICAO
					,@DATA DATA 
					,CV.TURNO
			FROM	[POLARIS02\BDIESBPROD].LYCEUM.DBO.LY_CANDIDATO A
			JOIN	[POLARIS02\BDIESBPROD].LYCEUM.DBO.LY_CONCURSO B ON A.CONCURSO = B.CONCURSO
			JOIN	[POLARIS02\BDIESBPROD].LYCEUM.DBO.LY_OPCOES_PROC_SELETIVO OP	ON A.CANDIDATO = OP.CANDIDATO
										AND A.CONCURSO = OP.CONCURSO
										AND ORDEM = '1'
			JOIN 	[POLARIS02\BDIESBPROD].LYCEUM.DBO.LY_OFERTA_CURSO CV 	ON CV.OFERTA_DE_CURSO = OP.OFERTA_DE_CURSO
										AND CV.CONCURSO  = OP.CONCURSO
			LEFT JOIN [POLARIS02\BDIESBPROD].LYCEUM.DBO.LY_CURSO CU ON CU.CURSO = CV.CURSO 
			WHERE	ANO			IN (
									SELECT	DISTINCT ANO
									FROM	[POLARIS02\BDIESBPROD].LYCEUM.DBO.IE_LY_OPCOES_APP
									WHERE	APLICACAO in ( 'VESTIBULAR','VESTIBULAR_EAD_TRIMESTRAL')
									)
			AND		A.CONCURSO	NOT LIKE	'%INTERESSE%'
			AND		SIT_CANDIDATO_VEST <> 'estorno'
			AND		NOME_COMPL NOT LIKE '%TESTE%'
			AND		NOME_COMPL IS NOT NULL
			AND		DT_INSCRICAO IS NOT NULL
			AND		convert(varchar, DT_INSCRICAO, 102)  <= @DATA

		
		
	FETCH NEXT FROM cursor_gera_financeiro 

	INTO  @DATA   
    

	END 
	CLOSE cursor_gera_financeiro 
	DEALLOCATE cursor_gera_financeiro 